### PR TITLE
Graphical Exception handling

### PR DESCRIPTION
**Pull request by festen**
Added a graphical catcher for uncatched exceptions so that the program doesn't quit but shows the exception

### CODE REVIEW

**Comment by alexwalterbos** [comment]
Does this save the state of the program? Could we attempt to do that before shutting down?

**Comment by festen** [comment]
You mean saving the GUI state? why would you want to do that? you could save the fittest canvas when an error occurs. You could save the stack trace to a log file or something.

**Comment by alexwalterbos** [comment]
No, the same thing you do with the save/load functionality

**Comment by festen** [comment]
You could, but lots of work because at this scope you don't know anything about the algorithm.
It saves a suspended state every 1000th epoch anyway so you can quickly recover if you have `save` checked while running your algorithm.

**Comment by alexwalterbos** [comment]
That's true! Nevermind, merging this.

**Pull request merged**
